#Web
 - hosts: all
   sudo: yes

   tasks:
    - name: Install nginx
      apt: name=nginx state=present

    - name: start nginx
      service:
          name: nginx
          state: started

    - name: Select content
      template: src=/vagrant/frontend_app/index.html dest=/var/www/html

   handlers:
    - name: Restart nginx
      service: name=nginx state=restarted