#Web
 - hosts: web
   sudo: yes
  
   tasks:
    - name: Install nginx
      apt: name=nginx state=present
    - name: content
      template: src=labo1_vagrant/frontend_app/index.html dest=/var/www/html/index.html

   handlers:
    - name: Restart nginx
      service: name=nginx state=restarted