#Loadbalancer
  - hosts: all
    sudo: yes

    tasks:
    - name: Install haproxy & socat
      apt:
        pkg:
          - haproxy
          - socat
        state: latest

    - name: Enable HAProxy
      lineinfile: dest=/etc/default/haproxy regexp="^ENABLED" line="ENABLED=1"
      notify: Restart HAProxy

    - name: Deploy HAProxy config
      template:
        src: /vagrant/cfg/haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
      notify: Restart HAProxy

    handlers:
      - name: Restart HAProxy
        service: name=haproxy state=restarted
